INSERT INTO address (street, zip_code, city, country) VALUES ('Zmaj Jovina 4',21000 , 'Novi Sad', 'Srbija');
INSERT INTO address (street, zip_code, city, country) VALUES ('Trg Majke Jevrosime 17 ',21000 , 'Novi Sad', 'Srbija');
INSERT INTO address (street, zip_code, city, country) VALUES ('Marije Bursac 15',21000 , 'Novi Sad', 'Srbija');
INSERT INTO address (street, zip_code, city, country) VALUES ('Milana Jesica Ibre 3',21000 , 'Novi Sad', 'Srbija');

INSERT INTO users (email, name, password, authorities, verified, address_id) VALUES ('nikolina@hotmail.rs','Nikolina' , '123', 'USER', true, 1);
INSERT INTO users (email, name, password, authorities, verified, address_id) VALUES ('jelena95@hotmail.rs','Jelena' , '123', 'USER', true, 2);
INSERT INTO users (email, name, password, authorities,   verified, address_id) VALUES ('zarko@hotmail.rs' ,'Zarko', '123', 'ADMIN', true, 3);
INSERT INTO users (email, name, password, authorities,   verified, address_id) VALUES ('milana@hotmail.rs','Milana' , '123', 'ADMIN',  true, 4);

INSERT INTO manufacturer (name)  VALUES ('Intel');
INSERT INTO manufacturer (name)  VALUES ('AMD');
INSERT INTO manufacturer (name)  VALUES ('ASUS');
INSERT INTO manufacturer (name)  VALUES ('SAMSUNG');
INSERT INTO manufacturer (name)  VALUES ('LG');
INSERT INTO manufacturer (name)  VALUES ('KINGSTON');

INSERT INTO component_type (name, cardinality, required) VALUES ('motherboard', '1',1 );
INSERT INTO component_type (name, cardinality, required) VALUES ('procesor', '1', 1 );
INSERT INTO component_type (name, cardinality, required) VALUES ('speaker', 'n', 0 );
INSERT INTO component_type (name, cardinality, required) VALUES ('keyboard', '1', 0 );
INSERT INTO component_type (name, cardinality, required) VALUES ('SSD', '1', 0 );
INSERT INTO component_type (name, cardinality, required) VALUES ('monitor', 'n', 1 );

INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('GIGABYTE GA-B250M-DS3H', '1' , '1', '60', '6000',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('GIGABYTE GA-B255M-SHJk', '1' , '1', '55', '6500',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('ASUS MB - SOCKET FM2+', '1' , '3', '60', '5300',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('ASUS MB - SOCKET 1150', '1' , '3', '55', '7000',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('Intel G4560', '2' , '1', '5', '3000',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('Intel I5', '2' , '2', '5', '5000',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('Intel I7', '2' , '1', '5', '7000',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('AMD Ryzen 7 1700X,', '2' , '2', '5', '4000',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('AMD Ryzen 7 1800X, ', '2' , '2', '5', '5000',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('AMD Athlon X4', '2' , '2', '5', '2500',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('LG Speaker PH5', '3' , '5', '25', '6000',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('LG Speaker PH1', '3' , '5', '25', '3000',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('LG Speaker PH3', '3' , '5', '25', '4000',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('KeyBoard  SKJ-3', '4' , '4', '55', '6000',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('KeyBoard  SKJ-4', '4' , '4', '60', '6000',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('KeyBoard  SKJ-5', '4' , '4', '15', '12000',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('KeyBoard  CK115', '4' , '6', '0', '1240',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('KeyBoard  CK135', '4' , '6', '53', '7000',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('KeyBoard  CK112', '4' , '6', '10', '2350',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('KeyBoard  CK62', '4' , '4', '42', '1250',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('KeyBoard  MK108', '4' , '4', '52', '3000',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('KeyBoard  Wireless', '4' , '4', '31', '6532',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('KeyBoard  Bluetooth', '4' , '4', '55', '6000',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('KeyBoard  Bluetooth', '4' , '4', '42', '6420',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('KeyBoard  Mechanical', '4' , '4', '24', '60000',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('ASUS LED 18.5', '6' , '4', '55', '13000',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('ASUS LED 18.5 E970SWN', '6' , '4', '55', '12000',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('SSDNow 120GB', '5' , '6', '30', '7600',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('SSDNow 240GB', '5' , '6', '78', '12700',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('SSD 1TB', '6' , '4', '50', '62200',true);
INSERT INTO components (name, typeid, manufacturer_id, quantity, price, active_status) VALUES ('SSD 512GB, ', '6' , '4', '112', '32800',true);

INSERT INTO configuration (configuration_status,name,user_id,pay_address_id,deliver_address_id, method_of_payment) VALUES ('0','Conf1',2,2,2, null);
INSERT INTO configuration (configuration_status,name,user_id,pay_address_id,deliver_address_id, method_of_payment) VALUES ('0','Conf2',2,2,2, null);
INSERT INTO configuration (configuration_status,name,user_id,pay_address_id,deliver_address_id, method_of_payment) VALUES ('0','Conf3',2,2,2, null);
INSERT INTO configuration (configuration_status,name,user_id,pay_address_id,deliver_address_id, method_of_payment) VALUES ('2','Conf4',2,2,2, "Money on delivery");
INSERT INTO configuration (configuration_status,name,user_id,pay_address_id,deliver_address_id, method_of_payment) VALUES ('3','Conf5',2,2,2, "Credit Card");
INSERT INTO configuration (configuration_status,name,user_id,pay_address_id,deliver_address_id, method_of_payment) VALUES ('1','Conf6',2,2,2, "Payment to account");
INSERT INTO configuration (configuration_status,name,user_id,pay_address_id,deliver_address_id, method_of_payment) VALUES ('0','Conf7',1,1,1, null);
INSERT INTO configuration (configuration_status,name,user_id,pay_address_id,deliver_address_id, method_of_payment) VALUES ('1','Conf8',1,1,1, "Payment to account");

INSERT INTO configuration_components (configuration_id,components_id) VALUES ('1','3');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('1','9');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('1','26');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('1','27');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('1','15');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('1','30');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('1','12');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('2','1');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('2','7');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('2','27');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('2','20');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('2','29');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('2','11');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('2','12');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('3','3');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('3','6');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('3','26');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('3','11');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('4','1');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('4','10');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('4','27');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('4','17');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('5','2');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('5','9');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('5','27');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('5','13');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('5','25');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('6','3');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('6','8');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('6','26');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('6','24');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('7','2');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('7','8');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('7','26');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('7','19');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('7','12');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('8','1');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('8','7');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('8','26');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('8','12');
INSERT INTO configuration_components (configuration_id,components_id) VALUES ('8','18');

INSERT INTO users_configurations (user_id,configurations_id) VALUES ('2','1');
INSERT INTO users_configurations (user_id,configurations_id) VALUES ('2','2');
INSERT INTO users_configurations (user_id,configurations_id) VALUES ('2','3');
INSERT INTO users_configurations (user_id,configurations_id) VALUES ('2','4');
INSERT INTO users_configurations (user_id,configurations_id) VALUES ('2','5');
INSERT INTO users_configurations (user_id,configurations_id) VALUES ('2','6');
INSERT INTO users_configurations (user_id,configurations_id) VALUES ('1','7');
INSERT INTO users_configurations (user_id,configurations_id) VALUES ('1','8');